"""Teste autogenerate

Revision ID: 43e067e9662c
Revises: 7401b0a2aeaf
Create Date: 2024-11-29 10:59:12.396172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e067e9662c'
down_revision: Union[str, None] = '7401b0a2aeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('option_1', sa.String(), nullable=True),
    sa.Column('option_2', sa.String(), nullable=True),
    sa.Column('vegan_option', sa.String(), nullable=True),
    sa.Column('vegetarian_option', sa.String(), nullable=True),
    sa.Column('salad_1', sa.String(), nullable=True),
    sa.Column('salad_2', sa.String(), nullable=True),
    sa.Column('garnish', sa.String(), nullable=True),
    sa.Column('side_1', sa.String(), nullable=True),
    sa.Column('side_2', sa.String(), nullable=True),
    sa.Column('side_3', sa.String(), nullable=True),
    sa.Column('juice', sa.String(), nullable=True),
    sa.Column('dessert', sa.String(), nullable=True),
    sa.Column('coffee', sa.String(), nullable=True),
    sa.Column('bread', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
