"""Create tables

Revision ID: 7401b0a2aeaf
Revises: 9dea51fc95cb
Create Date: 2024-11-29 10:07:54.098957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7401b0a2aeaf'
down_revision: Union[str, None] = '9dea51fc95cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('main_course', sa.String(), nullable=False),
    sa.Column('alternative_course', sa.String(), nullable=True),
    sa.Column('vegan_option', sa.String(), nullable=True),
    sa.Column('vegetarian_option', sa.String(), nullable=True),
    sa.Column('salads', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('drink', sa.String(), nullable=True),
    sa.Column('dessert', sa.String(), nullable=True),
    sa.Column('coffee', sa.String(), nullable=True),
    sa.Column('bread', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_date'), 'menu', ['date'], unique=False)
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_date'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
